site_name: Esp32-101-board
site_description: ESP32-101-board reference site

nav:
  - Начало: index.md
  - Инфо: boardInfo.md
  - Инсталиране IDE: ide-install.md
  - Библиотеки: 
    - Инсталиране на библиотека: libraries.md
    - Използвани в 101-board: libraries-onboard.md
    
  - Примери: 
    - 01. Бутони: examples/01-button.md
    - 02. Ротационен енкодер: examples/02-encoder.md
    - 03. RGB светодиод: examples/03-rgb.md
    - 04. Транзисторни цифрови изходи: examples/04-transistors.md
    - 05. Пиезо-зумер: examples/05-piezo.md
    - 06. Сензори за допир: examples/06-touch.md
    - 07. Аналогов джойстик: examples/07-joystick.md
    - 08. Температурен сензор: examples/08-temperature.md
    - 09. Фотодиод: examples/09-photodiode.md
    - 10. Инфрачервен светодиод: examples/10-infrared-tx.md
    - 11. Инфрачервен приемник с демодулатор (38kHz): examples/11-infrared-rx.md
    - 12. Графичен OLED дисплей : examples/12-display.md
    - 13. Жироскоп/акселерометър: examples/13-mems.md
    - 14. Допълнителна (външна) EEPROM памет: examples/14-onboard-eeprom.md
    - 99. Демо: examples/99-demo.md
    
  - Референция I/O: gpio.md
  - Notes:
    - ESP32_ADC: Notes/ESP32-ADC/ESP32-ADC.md
    - ESP32-DAC: Notes/ESP32-DAC/ESP32-DAC.md
    - ESP32-HAL: Notes/ESP32-HAL/ESP32-HAL.md
    - ESP32-LEDC: Notes/ESP32-LEDC/ESP32-LEDC.md
    - ESP32-TIMER: Notes/ESP32-TIMER/ESP32-TIMER.md
theme:
  name: material
  icon:
    logo: material/rocket-launch-outline
  favicon: img/rocket-launch-outline.png
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: electro
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.code.annotate

extra_css:
  - stylesheets/extra.css        
  - https://unpkg.com/mermaid@8.4.5/dist/mermaid.min.js

plugins:
  - markdownmermaid:
     init_options:
            - startOnLoad: true
            - theme: "forest"
            - themeCSS: ".node rect { fill: red; }"
            - flowchart:
                - curve: "cardinal"
                - useMaxWidth: true

markdown_extensions:
  - toc:
      title: "На тази страница"
      toc_depth: 1-4
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
     custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
